Document: repos.kbaranski.pl
Title: Debian repos.kbaranski.pl Manual
Author: <insert document author here>
Abstract: This manual describes what repos.kbaranski.pl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/repos.kbaranski.pl/repos.kbaranski.pl.sgml.gz

Format: postscript
Files: /usr/share/doc/repos.kbaranski.pl/repos.kbaranski.pl.ps.gz

Format: text
Files: /usr/share/doc/repos.kbaranski.pl/repos.kbaranski.pl.text.gz

Format: HTML
Index: /usr/share/doc/repos.kbaranski.pl/html/index.html
Files: /usr/share/doc/repos.kbaranski.pl/html/*.html
